package hibernatefestival;
// Generated 27-feb-2017 14:12:30 by Hibernate Tools 4.3.1



/**
 * Cartel generated by hbm2java
 */
public class Cartel  implements java.io.Serializable {


     private Integer id;
     private int festival;
     private int grupo;
     private boolean visible;

    public Cartel() {
    }

    public Cartel(int festival, int grupo, boolean visible) {
       this.festival = festival;
       this.grupo = grupo;
       this.visible = visible;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getFestival() {
        return this.festival;
    }
    
    public void setFestival(int festival) {
        this.festival = festival;
    }
    public int getGrupo() {
        return this.grupo;
    }
    
    public void setGrupo(int grupo) {
        this.grupo = grupo;
    }
    public boolean isVisible() {
        return this.visible;
    }
    
    public void setVisible(boolean visible) {
        this.visible = visible;
    }




}


