package hibernatefestival;
// Generated 27-feb-2017 14:12:30 by Hibernate Tools 4.3.1



/**
 * Grupo generated by hbm2java
 */
public class Grupo  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private int guitarraId;
     private int cantanteId;
     private boolean visible;

    public Grupo() {
    }

    public Grupo(String nombre, int guitarraId, int cantanteId, boolean visible) {
       this.nombre = nombre;
       this.guitarraId = guitarraId;
       this.cantanteId = cantanteId;
       this.visible = visible;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public int getGuitarraId() {
        return this.guitarraId;
    }
    
    public void setGuitarraId(int guitarraId) {
        this.guitarraId = guitarraId;
    }
    public int getCantanteId() {
        return this.cantanteId;
    }
    
    public void setCantanteId(int cantanteId) {
        this.cantanteId = cantanteId;
    }
    public boolean isVisible() {
        return this.visible;
    }
    
    public void setVisible(boolean visible) {
        this.visible = visible;
    }




}


